"""Unit tests for the fitsGBT module and it's main classes.

This test suit depends on there being the appropriate test fits data.  Please
run make_test_GBT_fits_file.py from this directory to generate this.  You will
need to point your system variables to some raw data.
"""

import unittest
import copy
import os

import scipy as sp
import numpy.ma as ma

import fitsGBT
import data_block as db
import kiyopy.custom_exceptions as ce

# This fits file generated by the script make_test_GBT_fits_file.py
testfile_gos = 'testdata/testfile_GBTfits.fits'
# This file has known properties:
bands_gos = (695, 725)
scans_gos = (17, 18)
pol_set = (-5, -7, -8, -6)
cal_set = ('T', 'F')
nband_gos = len(bands_gos)
nscan_gos = len(scans_gos)
ntime_gos = 10
npol_gos = len(pol_set)
ncal_gos = len(cal_set)
nchan_gos = npol_gos * ncal_gos
nfreq_gos = 2048



class TestHistory(unittest.TestCase) :
    """Tests that histories are read, added and written."""

    def setUp(self) :
        # testfile_gos has no history.
        self.reader = fits.SpecReader(testfile_gos, 0)

    def test_reads_history(self) :
        self.reader.hdulist[0].header.update('DB-HIST', 'First History')
        self.reader.hdulist[0].header.update('DB-DET', 'A Detail')
        Block1 = self.reader.read(0, 0)
        Block = self.reader.read(0, 1)
        self.assertTrue(Block.history.has_key('000: First History'))
        self.assertEqual(Block.history['000: First History'][0], 'A Detail')
        self.assertTrue(Block.history.has_key('001: Read from file.'))
        self.assertEqual(Block.history['001: Read from file.'][0], 
                        'File name: ' + testfile_gos)

    def test_writes_history(self) :
        # Mock up a work flow history
        Block1 = self.reader.read(0, 0)
        Block2 = self.reader.read(0, 1)
        Block1.add_history('Processed.', ('Processing detail 1',))
        Block2.add_history('Processed.', ('Processing detail 2',))
        hist_entry = ("This is a long history entry that is much longer than "
                      "80 characters and should cause a wrapping of the fits "
                      "history key.")
        hist_detail = ("We really want to check that the pyfits "
                       "mechanisms/any supporting code that Ive written can "
                       "properly deal with this.",)
        Block1.add_history(hist_entry, hist_detail)
        Block2.add_history(hist_entry, hist_detail)
        Writer = fits.SpecWriter((Block1, Block2), 0)
        Writer.write('temp2.fits')
        newReader = fits.SpecReader('temp2.fits', 0)
        newBlock = newReader.read(0,0)
        # These two line need to come before anything likly to fail.
        del newReader
        os.remove('temp2.fits')
        # See that we have all the history we expect.
        hist = newBlock.history
        self.assertTrue(hist.has_key('000: Read from file.'))
        self.assertEqual(len(hist['000: Read from file.']), 1)
        self.assertTrue(hist.has_key('001: Processed.'))
        self.assertEqual(len(hist['001: Processed.']), 2)
        self.assertEqual(hist['001: Processed.'][0], 'Processing detail 1')
        self.assertEqual(hist['001: Processed.'][1], 'Processing detail 2')
        self.assertTrue(hist.has_key('002: ' + hist_entry))
        self.assertEqual(len(hist['002: ' + hist_entry]), 1)
        self.assertEqual(hist['002: ' + hist_entry][0], hist_detail[0])
        self.assertTrue(hist.has_key('003: Written to file.'))
        self.assertEqual(len(hist['003: Written to file.']), 1)
        self.assertEqual(hist['003: Written to file.'][0], 'File name: ' + 
                         'temp2.fits')
        self.assertTrue(hist.has_key('004: Read from file.'))


    def tearDown(self) :
        del self.reader

        
                

if __name__ == '__main__' :
    unittest.main()

